DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
id BIGINT generated by default as identity not null,
name VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL,
CONSTRAINT pk_urls PRIMARY KEY (id)
);

CREATE TABLE url_checks (
id BIGINT generated by default as identity not null,
status_code INT,
title VARCHAR(255) NOT NULL,
h1 VARCHAR(255),
description TEXT,
url_id BIGINT,
created_at TIMESTAMP NOT NULL,
CONSTRAINT pk_url_checks PRIMARY KEY (id)
);

ALTER TABLE url_checks ADD CONSTRAINT fk_url_checks_url_id FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE RESTRICT ON UPDATE RESTRICT;